server:
  port: 8085

spring:
  application:
    name: alarm-service
  config:
    import: optional:configserver:http://ec2-15-164-164-245.ap-northeast-2.compute.amazonaws.com:8888
  profiles:
    active: dev
  cloud:
    config:
      name: secret

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://ec2-15-164-164-245.ap-northeast-2.compute.amazonaws.com:8761/eureka
      defaultZone: http://localhost:8761/eureka
